
# Vertex AI用パス (コメントアウト)
train: /app/datasets/house/train
val: /app/datasets/house/val

# ローカルでのディレクトリパス
# train: datasets/house/train
# val: datasets/house/val


# number of classes
nc: 5
# class names
names: ['Direction', 'Direction2', 'House', 'Road', 'Space']