names:
- 1F
- 2F
- CL1
- CL2
- CL3
- CL4
- CO
- D
- DN
- DR
- E
- H
- House
- K
- L
- North
- R1
- R2
- R3
- R4
- Road
- ST
- South
- Space
- UB
- UP
- WC
nc: 27
train: house/train/images
val: house/val/images
